language: c
sudo: false
addons:
  apt:
    sources:
      - r-packages-precise
    packages:
      - r-base-dev
      - r-recommended
      - pandoc
  postgresql: "9.4"
env:
  - R_LIBS_USER=~/.R/library
cache:
  directories:
    $R_LIBS_USER
before_script:
  - mkdir -p "$R_LIBS_USER"
  - Rscript -e 'if (length(find.package("devtools", quiet = TRUE)) == 0L) { install.packages("devtools", repos = "http://cran.rstudio.com") }'
  - Rscript -e 'devtools::update_packages("devtools", repos = "http://cran.rstudio.com")'
  - Rscript -e 'if (!require("roxygen")) devtools::install_github("klutometis/roxygen")'
  - Rscript -e 'if (!require("DBI")) devtools::install_github("rstats-db/DBI")'
  - Rscript -e 'if (!require("RPostgres")) devtools::install_github("robertzk/RPostgres@0.1.1")'
  - Rscript -e 'if (!require("testthat")) devtools::install_github("hadley/testthat")'
  - Rscript -e 'if (!require("testthatsomemore")) devtools::install_github("robertzk/testthatsomemore")'
  - Rscript -e 'if (!require("syberiaStructure")) devtools::install_github("robertzk/syberiaStructure")'
  - Rscript -e 'if (!require("berdie")) devtools::install_github("robertzk/berdie")'
  - Rscript -e 'if (!require("covr")) devtools::install_github("kirillseva/covr")'
  - Rscript -e 'if (!require("dbtest")) devtools::install_github("avantcredit/dbtest")'
  - Rscript -e 'if (!require("batchman")) devtools::install_github("peterhurford/batchman")'
  - Rscript -e 'devtools::install_deps(repos = "http://cran.rstudio.com", dependencies = TRUE)'
script:
  - Rscript -e 'res <- try(devtools::check()); quit(save = "no", status = if (isTRUE(res)) { 0 } else { 0 }, runLast = FALSE)'
  - "cat /tmp/$(ls /tmp | grep '^Rtmp')/cachemeifyoucan.Rcheck/00install.out"
after_success:
  - Rscript -e 'library(covr);coveralls()'
notifications:
  hipchat:
    rooms:
      secure: C/QSVCJr0J4eLU1IF+yFOc0Az5I2oZC/F61b1Gb3OHm2ZtLTTJY+tTD1xO0PMp+FRdDLkV9PpFWei3C+tPOMVQrzHgpB9YL3RCsHbghzH3C9O7eexQMEON1xh4cI+09F+N6CisIdeQYsUEaePZ2/sOGjo1tcBdwxSjKttGslZlw=
    on_success: change
    on_failure: change
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      | Details: %{build_url} | Changes: %{compare_url}"
